### ISSUE TITLE
Tateru service call error on boot

### ISSUE THREAD

**Issue by fyx** [tateru/tateru-installer#3] opened 2020-12-29 21:00 UTC
I noticed an unexpected error just before public key installed on boot up. Probably because network isn't fully initialized.
```
[  498.014474] rc.installer[430]: Tateru machine service returnd code 204, will retry
[  498.015413] rc.installer[430]: Tateru machine service returnd code 204, will retry
[  498.016344] rc.installer[430]: Tateru machine service returnd code 204, will retry
[  498.017354] rc.installer[430]: Tateru machine service returnd code 204, will retry
[  498.018453] rc.installer[430]: Tateru machine service returnd code 204, will retry
[  498.019684] rc.installer[430]: Tateru machine service returnd code 204, will retry
[  498.020792] rc.installer[430]: Tateru machine service returnd code 204, will retry
[  498.021863] rc.installer[430]: Tateru machine service returnd code 204, will retry
[  498.022797] rc.installer[430]: Tateru machine service returnd code 204, will retry
[  498.023737] rc.installer[430]: Tateru machine service returnd code 204, will retry
[  498.024720] rc.installer[430]: Tateru machine service returnd code 204, will retry
[  498.025813] rc.installer[430]: Unexpected Tateru service call error: <class 'requests.>
[  498.027053] rc.installer[430]: SSH public key installed
```

**Comment by bluecmd** [comment] 2020-12-29 22:13
@fyx is unable to reproduce this error with #4 merged, will close for now.

**Closed as completed by bluecmd** 2020-12-29 22:13 UTC
Labels: bug
